openapi: 3.0.2
info:
  title: Wuhan2020 API service
  description: This is the API service of the Wuhan2020 project, which aims at collecting all useful information to help people fight against the 2019-nCoV outbreak, check the developer website for more info
  version: 0.1.0
  contact:
    name: "Github Repo"
    url: https://github.com/wuhan2020/api-server

# Let's version the APIs a bit later
# servers:
#   - url: /api/v1

tags:
  - name: Wuhan2020 Data
    description: Get data that's collected and validated by Wuhan2020 volunteers

# Refer to https://swagger.io/docs/specification/using-ref/ for Escape Characters e.g. ~1
paths:
  /accommodation/all:
    $ref: "accommodations.yml#/paths/~1accommodation~1all"
  /hospital/all:
    $ref: "hospitals.yml#/paths/~1hospital~1all"
components:
  schemas:
    AccommodationItem:
      $ref: "accommodations.yml#/components/schemas/AccommodationItem"
    HospitalItem:
      $ref: "hospitals.yml#/components/schemas/HospitalItem"
