openapi: 3.0.2
info:
  title: Wuhan2020 API service
  description: This is the API service of the Wuhan2020 project, which aims at collecting all useful information to help people fight against the 2019-nCoV outbreak, check the developer website for more info
  version: 0.1.0
  contact:
    name: "Github Repo"
    url: https://github.com/wuhan2020/api-server

# Let's version the APIs a bit later
# servers:
#   - url: /api/v1

tags:
  - name: Wuhan2020 Data
    description: Get data that's collected and validated by Wuhan2020 volunteers

paths:
  $ref: "accommodations.yml#/paths"
components:
  $ref: "accommodations.yml#/components/schemas"
